#!/bin/bash
#SBATCH --output=/data/hpcdata/users/josnez/jobs/SE_ocean_%j_%N.out
#SBATCH --error=/data/hpcdata/users/josnez/jobs/SE_ocean_%j_%N.err
#SBATCH --job-name=Single_Eddy
#SBATCH --mem=32gb
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --partition=gpu
#SBATCH --account=gpu
#SBATCH --chdir=.
#SBATCH --gres=gpu:1
#SBATCH --nodelist=bsl-node-s22


export JULIA_CUDA_MEMORY_POOL=none

cd $SLURM_SUBMIT_DIR

date

julia --project run.jl C-0

date
